In [226]:
#Getting our initial project setup started
import os
import pandas as pd

#Note: Generally in this project I will be leaving a lot of statements printed that in a normal script I would 
#print and then comment out; this is for demonstration purposes. 

#Checking the files in our directory
#os.getcwd()
os.listdir(os.getcwd())

#I found the data using the proton Lumo AI tool to find the Army Core of Engineers Website 
#And then after looking there found some datasets that might be interesting 
#https://ndc.ops.usace.army.mil/wcsc/webpub/#/report-landing/year/2024/region/3/location/3756

['Milwaukee5YearCargoReport-Domestic.csv',
 'README.md',
 'wcusgl23.pdf',
 'Greenbay5YearCargoReport-Domestic.csv',
 '.ipynb_checkpoints',
 'Milwaukee5YearCargoReport-Foreign.csv',
 'Greenbay5YearCargoReport-Foreign.csv',
 'My First Jupyter Notebook.ipynb',
 '.git',
 '.Rhistory']

In [227]:
#Some potential questions we could ask 
#1. How many different products were shipped throught Milwaukee and Green Bay respectively?
#   a) Is there a large overlap or are the categories mainly seperate? 
#   b) What are the comparisons in gross tonnage? 

#3. Has the amount changed much over time? 
#   a) Is there a decrease in shipping during 2020 that could be related to the covid-19 pandemic? 
#   b) Are there different patterns in domestic and foreign shipments? 

#4 How much does foreign vs. domestic shipping play a role in between the two ports? 
#  a) How much domestic shipping and recieving is there? 
#  b) How much foreign shipping and recieving is there?

In [228]:
#Reading in some datasets
#These datasest contain information about shipped goods per calendar year to the ports of Milwaukee and Green Bay
#respectively, with units in the thousands of short tons (i.e. 2 thousand pounds) of cargo. I seperately downloaded 
#the files with information for domestic and foreign shipping, the definitions of which are in the report these 
#numbers are derived from. I have also looked at the same datasets in the report itself. 

#Loading in the datasets for Milwaukee
milwaukee_domestic=pd.read_csv('Milwaukee5YearCargoReport-Domestic.csv')
milwaukee_foreign=pd.read_csv('Milwaukee5YearCargoReport-Foreign.csv')

print("Milwaukee Domestic")
print(milwaukee_domestic.info())
print("Milwaukee Foreign")
print(milwaukee_foreign.info())

Milwaukee Domestic
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              43 non-null     str
 1   Unnamed: 1              43 non-null     str
 2   All Traffic Directions  43 non-null     str
 3   Unnamed: 3              43 non-null     str
 4   Unnamed: 4              43 non-null     str
 5   Unnamed: 5              43 non-null     str
 6   Unnamed: 6              43 non-null     str
 7   Intraport               43 non-null     str
 8   Unnamed: 8              43 non-null     str
 9   Unnamed: 9              43 non-null     str
 10  Unnamed: 10             43 non-null     str
 11  Unnamed: 11             43 non-null     str
 12  Receipts                43 non-null     str
 13  Unnamed: 13             43 non-null     str
 14  Unnamed: 14             43 non-null     str
 15  Unnamed: 15             43 non-null     str
 16  Unnamed: 16             43 non-null     str
 17  Shipments               43 non-null     str
 18  Unnamed: 18             43 non-null     str
 19  Unnamed: 19             43 non-null     str
 20  Unnamed: 20             43 non-null     str
 21  Unnamed: 21             43 non-null     str
dtypes: str(22)
memory usage: 9.8 KB
None
Milwaukee Foreign
<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              43 non-null     str
 1   Unnamed: 1              43 non-null     str
 2   All Traffic Directions  43 non-null     str
 3   Unnamed: 3              43 non-null     str
 4   Unnamed: 4              43 non-null     str
 5   Unnamed: 5              43 non-null     str
 6   Unnamed: 6              43 non-null     str
 7   Intraport               43 non-null     str
 8   Unnamed: 8              43 non-null     str
 9   Unnamed: 9              43 non-null     str
 10  Unnamed: 10             43 non-null     str
 11  Unnamed: 11             43 non-null     str
 12  Receipts                43 non-null     str
 13  Unnamed: 13             43 non-null     str
 14  Unnamed: 14             43 non-null     str
 15  Unnamed: 15             43 non-null     str
 16  Unnamed: 16             43 non-null     str
 17  Shipments               43 non-null     str
 18  Unnamed: 18             43 non-null     str
 19  Unnamed: 19             43 non-null     str
 20  Unnamed: 20             43 non-null     str
 21  Unnamed: 21             43 non-null     str
dtypes: str(22)
memory usage: 9.7 KB
None

In [229]:
#Green Bay 
greenbay_domestic=pd.read_csv('Greenbay5YearCargoReport-Domestic.csv')
greenbay_foreign=pd.read_csv('Greenbay5YearCargoReport-Foreign.csv')

print("Green Bay Domestic")
print(greenbay_domestic.info())
print("Green Bay Foreign")
print(greenbay_foreign.info())

Green Bay Domestic
<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              31 non-null     str
 1   Unnamed: 1              31 non-null     str
 2   All Traffic Directions  31 non-null     str
 3   Unnamed: 3              31 non-null     str
 4   Unnamed: 4              31 non-null     str
 5   Unnamed: 5              31 non-null     str
 6   Unnamed: 6              31 non-null     str
 7   Intraport               31 non-null     str
 8   Unnamed: 8              31 non-null     str
 9   Unnamed: 9              31 non-null     str
 10  Unnamed: 10             31 non-null     str
 11  Unnamed: 11             31 non-null     str
 12  Receipts                31 non-null     str
 13  Unnamed: 13             31 non-null     str
 14  Unnamed: 14             31 non-null     str
 15  Unnamed: 15             31 non-null     str
 16  Unnamed: 16             31 non-null     str
 17  Shipments               31 non-null     str
 18  Unnamed: 18             31 non-null     str
 19  Unnamed: 19             31 non-null     str
 20  Unnamed: 20             31 non-null     str
 21  Unnamed: 21             31 non-null     str
dtypes: str(22)
memory usage: 7.3 KB
None
Green Bay Foreign
<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              31 non-null     str
 1   Unnamed: 1              31 non-null     str
 2   All Traffic Directions  31 non-null     str
 3   Unnamed: 3              31 non-null     str
 4   Unnamed: 4              31 non-null     str
 5   Unnamed: 5              31 non-null     str
 6   Unnamed: 6              31 non-null     str
 7   Intraport               31 non-null     str
 8   Unnamed: 8              31 non-null     str
 9   Unnamed: 9              31 non-null     str
 10  Unnamed: 10             31 non-null     str
 11  Unnamed: 11             31 non-null     str
 12  Receipts                31 non-null     str
 13  Unnamed: 13             31 non-null     str
 14  Unnamed: 14             31 non-null     str
 15  Unnamed: 15             31 non-null     str
 16  Unnamed: 16             31 non-null     str
 17  Shipments               31 non-null     str
 18  Unnamed: 18             31 non-null     str
 19  Unnamed: 19             31 non-null     str
 20  Unnamed: 20             31 non-null     str
 21  Unnamed: 21             31 non-null     str
dtypes: str(22)
memory usage: 7.0 KB
None

In [230]:
#Both datasets seem to have the same columns,though the rows are different between the 
#two cities. Notably right away Milwaukee seems to have more rows, so presumably a wider 
#variety of cargo products. 

#Let's view one of the datasets up more close to see if the column names could make more sense
milwaukee_domestic.head()

,Unnamed: 0,Unnamed: 1,All Traffic Directions,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Intraport,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Receipts,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Shipments,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,Code,Commodity,CY2024,CY2023,CY2022,CY2021,CY2020,CY2024,CY2023,CY2022,CY2021,CY2020,CY2024,CY2023,CY2022,CY2021,CY2020,CY2024,CY2023,CY2022,CY2021,CY2020
1,0,All Commodities,1185662,1393249,1137952,1283188,1266953,0,30,210,0,10,1091500,1052410,1065709,1044222,1115041,94162,340809,72033,238966,151902
2,2211,Gasoline,0,28744,6640,13002,0,0,0,0,0,0,0,0,0,0,0,0,28744,6640,13002,0
3,2330,Distillate Fuel Oil,0,7614,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7614,0,0,0
4,2429,Naphtha & Solvents,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [231]:
#After looking we see that the first two columns have identifying information for the rows, and the rest are 
#repeating information from 2024 to 2020 across the different shipping categories. We can definitely rename these to 
#clean the datasets more. We could alternatively split these dataframes into to smaller datasets for each shipping category, 
#but this seems unnecessary. 

#Let's develop some standardized column names
top_col_names=milwaukee_domestic.columns
print(top_col_names)
bot_col_names=milwaukee_domestic.iloc[0,:].astype('str')
print(bot_col_names)

#Trying to create new names using for loops 
test_col_names=top_col_names;print(test_col_names)
#Normally I would process with some form of a string search with grep for all the unknowns but I'm going to try 
#something different to test my limitations 

#testing a dictionary for the numbers in column names to label them
test_dict={"Empty":range(0,1)};print(test_dict["Empty"]);0 in test_dict["Empty"];#for i in range(0,2): print(i)

#"0" in test_col_names[0]

#creating a dictionary for the relabeling
top_nyms={"Empty":range(0,2),"All Traffic Directions":range(3,7),"Intraport":range(8,12),"Receipts":range(13,17),"Shipments":range(18,22)}
#print(top_nyms)

top_col_names=top_col_names.str.replace(pat="Unnamed: ",repl='',regex=False)
#print(top_col_names);"0" in [str(i) for i in range(0,1)]

#if "0" in 
print("space")

#for i in range(0,len(top_col_names)): 
#    if top_col_names[i] in [str(j) for j in top_nyms["Empty"]]:
#        print(top_col_names[i])
print(top_col_names)
top_col_names=top_col_names.to_list()
#with a lot of trial and error I realized that top_col_names is a index object instead of a list so we 
#will be changing this otherwise the below loop is not possible 

for i in range(0,len(top_col_names)): 
    if top_col_names[i] in [str(j) for j in top_nyms["Empty"]]:
        print(top_col_names[i]); top_col_names[i]=""
    elif top_col_names[i] in [str(j) for j in top_nyms["All Traffic Directions"]]:
        top_col_names[i]="alltrafficdirections"
    elif top_col_names[i] in [str(j) for j in top_nyms["Intraport"]]:
        top_col_names[i]="intraport"
    elif top_col_names[i] in [str(j) for j in top_nyms["Receipts"]]:
        top_col_names[i]="receipts"
    elif top_col_names[i] in [str(j) for j in top_nyms["Shipments"]]:
        top_col_names[i]="shipments"

print(top_col_names)

#combining For full names and some final cleanup
new_col_names=top_col_names+bot_col_names;new_col_names=new_col_names.to_list()
new_col_names=[j.replace(' ','').replace('CY','').lower() for j in new_col_names ]
print(new_col_names)

Index(['Unnamed: 0', 'Unnamed: 1', 'All Traffic Directions', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Intraport', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Receipts', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Shipments', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21'],
      dtype='str')
Unnamed: 0                     Code
Unnamed: 1                Commodity
All Traffic Directions       CY2024
Unnamed: 3                   CY2023
Unnamed: 4                   CY2022
Unnamed: 5                   CY2021
Unnamed: 6                   CY2020
Intraport                    CY2024
Unnamed: 8                   CY2023
Unnamed: 9                   CY2022
Unnamed: 10                  CY2021
Unnamed: 11                  CY2020
Receipts                     CY2024
Unnamed: 13                  CY2023
Unnamed: 14                  CY2022
Unnamed: 15                  CY2021
Unnamed: 16                  CY2020
Shipments                    CY2024
Unnamed: 18                  CY2023
Unnamed: 19                  CY2022
Unnamed: 20                  CY2021
Unnamed: 21                  CY2020
Name: 0, dtype: str
Index(['Unnamed: 0', 'Unnamed: 1', 'All Traffic Directions', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Intraport', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Receipts', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Shipments', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21'],
      dtype='str')
range(0, 1)
space
Index(['0', '1', 'All Traffic Directions', '3', '4', '5', '6', 'Intraport',
       '8', '9', '10', '11', 'Receipts', '13', '14', '15', '16', 'Shipments',
       '18', '19', '20', '21'],
      dtype='str')
0
1
['', '', 'All Traffic Directions', 'alltrafficdirections', 'alltrafficdirections', 'alltrafficdirections', 'alltrafficdirections', 'Intraport', 'intraport', 'intraport', 'intraport', 'intraport', 'Receipts', 'receipts', 'receipts', 'receipts', 'receipts', 'Shipments', 'shipments', 'shipments', 'shipments', 'shipments']
['code', 'commodity', 'alltrafficdirections2024', 'alltrafficdirections2023', 'alltrafficdirections2022', 'alltrafficdirections2021', 'alltrafficdirections2020', 'intraport2024', 'intraport2023', 'intraport2022', 'intraport2021', 'intraport2020', 'receipts2024', 'receipts2023', 'receipts2022', 'receipts2021', 'receipts2020', 'shipments2024', 'shipments2023', 'shipments2022', 'shipments2021', 'shipments2020']

In [232]:
#Now with our new string we can relable the columns, let's just check that all our columns are the same across the 
#datasets

print("Data frame columns match") 
print(all((milwaukee_domestic.columns == milwaukee_foreign.columns) & (milwaukee_foreign.columns==greenbay_domestic.columns)
    & (greenbay_domestic.columns==greenbay_foreign.columns)))

print("First row columns match")
print(all((milwaukee_domestic.iloc[0,:] == milwaukee_foreign.iloc[0,:]) & (greenbay_domestic.iloc[0,:] == milwaukee_foreign.iloc[0,:])
& (greenbay_domestic.iloc[0,:] == greenbay_foreign.iloc[0,:])))


#adjusting our dataframes, making sure to check our inital one first 
milwaukee_domestic.columns=new_col_names#;milwaukee_domestic.info()
milwaukee_domestic=milwaukee_domestic.iloc[1:,:]#;milwaukee_domestic.head()

milwaukee_foreign.columns=new_col_names;milwaukee_foreign=milwaukee_foreign.iloc[1:,:]
greenbay_foreign.columns=new_col_names;greenbay_foreign=greenbay_foreign.iloc[1:,:]
greenbay_domestic.columns=new_col_names;greenbay_domestic=greenbay_domestic.iloc[1:,:]
greenbay_domestic.head(2)#looks good

Data frame columns match
True
First row columns match
True

,code,commodity,alltrafficdirections2024,alltrafficdirections2023,alltrafficdirections2022,alltrafficdirections2021,alltrafficdirections2020,intraport2024,intraport2023,intraport2022,intraport2021,intraport2020,receipts2024,receipts2023,receipts2022,receipts2021,receipts2020,shipments2024,shipments2023,shipments2022,shipments2021,shipments2020
1,0,All Commodities,1458894,1458303,1402256,1417625,1411271,0,0,17993,0,0,1344104,1406395,1327278,1370684,1342449,114790,51908,56985,46941,68822
2,1100,Coal & Lignite,154468,131755,220563,158579,222034,0,0,17993,0,0,119038,131755,202570,158579,222034,35430,0,0,0,0

In [233]:
#Now that we have a our columns set, we need to check if there's any other ways the data needs to be cleaned

#We could potentially remove the code column of the dataframe by setting the commodity code as the row index,
#this could also then be used as keys for merging the datframes if we were interested
greenbay_domestic.info()
greenbay_domestic.head()

#looking at one of the dataframes, the data types for all columns are listed as strings. We will need to convert 
#these to either integers or floats to analyze our data as well. Then we will see if there are any missing values, 
#though I think since this is technically a census of all the cargo in the ports there should not be any.

#After all this is done we should be ready to compute summary statistics and other information from the datasets

#Note: We will not being any hypothesis testing for this, partly because that's not the point of this project 
#but also because the information we are dealing with is already summary statistics that should be a census of all the 
#shipping done in the two ports. 

selected_cols=[0]+[*range(2,len(milwaukee_foreign.columns))]
milwaukee_domestic.iloc[:,selected_cols]

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 1 to 30
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   code                      30 non-null     str
 1   commodity                 30 non-null     str
 2   alltrafficdirections2024  30 non-null     str
 3   alltrafficdirections2023  30 non-null     str
 4   alltrafficdirections2022  30 non-null     str
 5   alltrafficdirections2021  30 non-null     str
 6   alltrafficdirections2020  30 non-null     str
 7   intraport2024             30 non-null     str
 8   intraport2023             30 non-null     str
 9   intraport2022             30 non-null     str
 10  intraport2021             30 non-null     str
 11  intraport2020             30 non-null     str
 12  receipts2024              30 non-null     str
 13  receipts2023              30 non-null     str
 14  receipts2022              30 non-null     str
 15  receipts2021              30 non-null     str
 16  receipts2020              30 non-null     str
 17  shipments2024             30 non-null     str
 18  shipments2023             30 non-null     str
 19  shipments2022             30 non-null     str
 20  shipments2021             30 non-null     str
 21  shipments2020             30 non-null     str
dtypes: str(22)
memory usage: 7.0 KB

,code,alltrafficdirections2024,alltrafficdirections2023,alltrafficdirections2022,alltrafficdirections2021,alltrafficdirections2020,intraport2024,intraport2023,intraport2022,intraport2021,intraport2020,receipts2024,receipts2023,receipts2022,receipts2021,receipts2020,shipments2024,shipments2023,shipments2022,shipments2021,shipments2020
1,0,1185662,1393249,1137952,1283188,1266953,0,30,210,0,10,1091500,1052410,1065709,1044222,1115041,94162,340809,72033,238966,151902
2,2211,0,28744,6640,13002,0,0,0,0,0,0,0,0,0,0,0,0,28744,6640,13002,0
3,2330,0,7614,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7614,0,0,0
4,2429,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,2430,93632,66807,97009,89429,80469,0,0,0,0,0,93632,66807,97009,89429,80469,0,0,0,0,0
6,2640,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,3220,0,0,0,52,14245,0,0,0,0,0,0,0,0,0,0,0,0,0,52,14245
8,3297,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,4310,898,0,0,0,0,0,0,0,0,0,0,0,0,0,0,898,0,0,0,0
10,4322,62120,91931,92884,76692,53542,0,0,0,0,0,61632,91931,92884,76692,53542,488,0,0,0,0
11,4323,42282,0,0,0,0,0,0,0,0,0,42282,0,0,0,0,0,0,0,0,0
12,4331,0,0,54988,56826,56485,0,0,0,0,0,0,0,54788,56826,56485,0,0,200,0,0
13,4335,57866,243195,5793,36174,25351,0,0,0,0,0,0,0,0,0,0,57866,243195,5793,36174,25351
14,4420,0,0,0,1580,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1580,0
15,4783,192668,212136,139315,131648,54084,0,0,0,0,0,192668,212136,139315,131648,54084,0,0,0,0,0
16,4860,83065,40203,38008,64443,154784,0,0,0,0,0,48505,1337,2454,0,82133,34560,38866,35554,64443,72651
17,5220,652781,676000,679259,689487,787268,0,0,0,0,0,652781,676000,679259,689487,787268,0,0,0,0,0
18,5312,0,4199,0,0,0,0,0,0,0,0,0,4199,0,0,0,0,0,0,0,0
19,5320,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,5330,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,5360,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,5370,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,5390,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,5421,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
25,5422,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,5429,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,5480,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28,6241,0,21900,6068,12543,24488,0,0,0,0,0,0,0,0,0,0,0,21900,6068,12543,24488
29,6344,0,0,4434,51782,1540,0,0,0,0,0,0,0,0,0,0,0,0,4434,51782,1540
30,6447,0,0,0,4326,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4326,0
31,6522,0,0,12384,46129,12407,0,0,0,0,0,0,0,0,0,0,0,0,12384,46129,12407
32,6590,0,0,0,3791,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3791,0
33,6747,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
34,6782,0,0,0,1594,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1594,0
35,6889,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
36,7110,350,520,1170,3640,2290,0,30,210,0,10,0,0,0,140,1060,350,490,960,3500,1220
37,7120,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
38,7230,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
39,7400,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
40,7500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
41,7600,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42,7900,0,0,0,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,50,0

In [234]:
#making our columns floats 
selected_cols=[0]+[*range(2,len(milwaukee_foreign.columns))]

milwaukee_domestic[milwaukee_domestic.columns[selected_cols]]=milwaukee_domestic[milwaukee_domestic.columns[selected_cols]].astype('int64')
milwaukee_foreign[milwaukee_foreign.columns[selected_cols]]=milwaukee_foreign[milwaukee_foreign.columns[selected_cols]].astype('int64')

greenbay_domestic[greenbay_domestic.columns[selected_cols]]=greenbay_domestic[greenbay_domestic.columns[selected_cols]].astype('int64')
greenbay_foreign[greenbay_foreign.columns[selected_cols]]=greenbay_foreign[greenbay_foreign.columns[selected_cols]].astype('int64')

#greenbay_foreign.info()
#greenbay_foreign.head()


#changing our row names 
milwaukee_domestic.index=milwaukee_domestic['code'];milwaukee_domestic=milwaukee_domestic.drop('code',axis=1)
milwaukee_foreign.index=milwaukee_foreign['code'];milwaukee_foreign=milwaukee_foreign.drop('code',axis=1)

greenbay_domestic.index=greenbay_domestic['code'];greenbay_domestic=greenbay_domestic.drop('code',axis=1)
greenbay_foreign.index=greenbay_foreign['code'];greenbay_foreign=greenbay_foreign.drop('code',axis=1)

#greenbay_foreign.head()


#these are all set up now

In [236]:
#Now we can start actually looking at some of the data. We'll start by choosing some specific questions based
#on our list earlier 

#note:another idea I had is looking at the top ranked tonnages each year

#Let's just fully print out one of the datframes and see what comes up to start
pd.set_option("display.max_rows", None, "display.max_columns", None)
#display(greenbay_domestic)

#so there are some rows in this table with only zeros. I assume that if there were no trade in the port at all, 
#the commodity would not be listed in the first place. Textile products with code 7500 is an example of a row with 
#no recorded tonnages

#print(greenbay_domestic.loc[7500,:])
#print(greenbay_foreign.loc[7500,:])

#There were 12 tons of textile products recieved from foreign imports in 2024, so this looks to be the case.

commodity                   Textile Products
alltrafficdirections2024                   0
alltrafficdirections2023                   0
alltrafficdirections2022                   0
alltrafficdirections2021                   0
alltrafficdirections2020                   0
intraport2024                              0
intraport2023                              0
intraport2022                              0
intraport2021                              0
intraport2020                              0
receipts2024                               0
receipts2023                               0
receipts2022                               0
receipts2021                               0
receipts2020                               0
shipments2024                              0
shipments2023                              0
shipments2022                              0
shipments2021                              0
shipments2020                              0
Name: 7500, dtype: object
commodity                   Textile Products
alltrafficdirections2024                  12
alltrafficdirections2023                   0
alltrafficdirections2022                   0
alltrafficdirections2021                   0
alltrafficdirections2020                   0
intraport2024                              0
intraport2023                              0
intraport2022                              0
intraport2021                              0
intraport2020                              0
receipts2024                              12
receipts2023                               0
receipts2022                               0
receipts2021                               0
receipts2020                               0
shipments2024                              0
shipments2023                              0
shipments2022                              0
shipments2021                              0
shipments2020                              0
Name: 7500, dtype: object